# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL6ZdVZQL1sDmyYsJQzp8PSTG5147RyZ
"""

!apt-get install openslide-tools
!pip install openslide-python tiatoolbox

from tiatoolbox.wsicore.wsireader import WSIReader
import matplotlib.pyplot as plt

# Set the path to your WSI image file
wsi_path = '/home/ubuntu/sudarsan/tiatoolbox/tiatoolbox/examples/examples_py/tiatoolbox_impart/63.svs'  # Replace with your actual file path

# Load the WSI
wsi = WSIReader.open(wsi_path)

# Read the whole slide image at the lowest resolution level (thumbnail)
img = wsi.slide_thumbnail()

# Save the thumbnail image
output_path = '/home/ubuntu/sudarsan/tiatoolbox/tiatoolbox/examples/examples_py/tiatoolbox_impart/wsi.png'
plt.imsave(output_path, img)

# Display the thumbnail
plt.imshow(img)
plt.axis('off')
plt.show()

print(f"Thumbnail saved at: {output_path}")